name: vibration
description: A plugin for handling Vibration API on iOS, Android, and web.
version: 1.7.4
homepage: https://github.com/benjamindean/flutter_vibration

environment:
  sdk: ">=2.12.1 <=2.17.6"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  vibration_web: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.benjaminabel.vibration
        pluginClass: VibrationPlugin
      ios:
        pluginClass: VibrationPlugin
      web:
        default_package: vibration_web
