name: vibration
description: A plugin for handling Vibration API on iOS and Android devices
version: 1.6.1
homepage: https://github.com/benjamindean/flutter_vibration

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  vibration_web: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.benjaminabel.vibration
        pluginClass: VibrationPlugin
      ios:
        pluginClass: VibrationPlugin
      web:
        default_package: vibration_web
